#!/bin/bash
cFlag=0
oFlag=0
dFlag=0

while getopts "cdo:" opt; do
   case $opt in
       c)
           cFlag=1
           ;;
       d)
           dFlag=1
           ;;
       o)
           oFlag=1
           oFile=$OPTARG
           ;;
       --)
           break;;
       \?)
           echo "Opcion inválida: -$OPTARG" >&2
           exit 1
           ;;
       :)
           echo "Option -$OPTARG requires an argument." >&2
           exit 1
           ;;
   esac
done

shift $(( OPTIND - 1 ))

if [ $cFlag -eq 1 ]
then
    if [ $oFlag -eq 1 ]
    then
        outFile="-o $oFile"
    fi
    if [ $dFlag -eq 1 ]
    then
        debug="-d"
    fi
    compilador/compiler $debug $outFile -- $@
else
    php -f vm/phast_vm.php $@
fi
