#!/bin/bash

# if [ -z $1 ]; then
#     echo "Se debe especificar un archivo para compilar o asi..."
# else
#     ruby compilador/ruby/driver.rb $1
# fi
#Manejo de opciones
    args=`getopt c: $*`
           # you should not use `getopt abo: "$@"` since that would parse
           # the arguments differently from what the set command below does.
           if [ $? != 0 ]
           then
                   echo 'Se debe especificar un archivo para ejecutar...'
                   exit 2
           fi
           set -- $args
           # You cannot use the set command with a backquoted getopt directly,
           # since the exit code from getopt would be shadowed by those of set,
           # which is zero by definition.
           for i
           do
                   case "$i"
                   in
                           -c)
                                   ruby compilador/ruby/driver.rb $2
                                   shift;;
                           --)
                                   echo "Maquina virtual.... -> $2"
                                   shift; break;;
                   esac
           done
