#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative 'lib/Quad'
require_relative 'lib/Scope'
require_relative 'lib/Var'
require_relative 'lib/Arr'
require_relative 'lib/Instrucciones'

module Phast
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 148)

    def initialize(scanner)
        #Lexico
        @scanner = scanner
        @curr_token = nil #Token en análisis
        @prev_token = nil #Token anterior

        #Scopes
        @scopes = {:global => Scope.new(nil), :constantes => Scope.new(nil)} #Hash de objetos Scope
        @scopes[:constantes].variables[:lng_ver] = Var.new(1.0,3,1.0,0,-1)
        @scope_actual = @scopes[:global]
        
        #Pilas
        @pOper = [] #Pila de operadores
        @pOperandos = [] #Pila de operandos (Vars)
        @pSaltos = [] #Pila para saltos (if,else, etc.)
        @pFnCall = [] #Pila de llamadas pendientes (Quads)
        @funToCall = []
        
        @pArr = []

    end

    def parse #Parsea mami parsea
        do_parse
        process_output
    end

    def next_token  #Correr tokens
        @prev_token = @curr_token
        @curr_token = @scanner.next_token
    end

    def openArreglo
        tmp = ArrDefinition.new(Var.new(nil,nil,nil,@scope_actual.temporales.length,nil))
        @scope_actual.temporales.push tmp.id
        @pArr.push tmp
    end

    def closeArreglo
        arr = @pArr.pop
        genera(Phast::ARRDEC,arr.length,nil,arr.id)
        arr.initQuads.each do |q|
            @scope_actual.quads.push q
        end
        @pOperandos.push arr.id
    end

    def copy_value de
        @pArr.last.initQuads.push Quad.new(Phast::ARRINI, de, nil, @pArr.last.length)
        @pArr.last.length += 1
    end

    def llame_var cual
        if @pArr.last != nil
            if !@scope_actual.variables.include? cual
                de_donde = guarda_cte("NULL",nil,0)
                copy_value de_donde
            else
                de_donde = @scope_actual.variables[cual]
                copy_value de_donde
            end
        else
            if @scope_actual.variables.include? cual
                @scope_actual.variables[cual]
            else
                guarda_var cual
            end
        end
    end

    def guarda_var nombre
        @scope_actual.variables[nombre] = Var.new(nombre,nil,nil,@scope_actual.variables.length,$lineno)
    end

    def guarda_cte(nombre,valor,tipo)
        if !@scopes[:constantes].variables.include? nombre
            @scopes[:constantes].variables[nombre] = Var.new(valor,tipo,valor,@scopes[:constantes].variables.length,$lineno)
        else
            return @scopes[:constantes].variables[nombre]
        end
    end

    def llama_cte nombre
        cte = @scopes[:constantes].variables[nombre]
        if @pArr.last != nil
            copy_value cte
        end
        return cte
    end

    def vaciar_pOperandos
        while !@pOperandos.empty?
            @pOperandos.pop
        end
    end

    def aumenta_scope nombre
        nuevo_scope = Scope.new(@scope_actual)
        @scope_actual = nuevo_scope
        @scopes[nombre] = @scope_actual
    end

    def disminuye_scope
        @scope_actual = @scope_actual.papa
    end
    
    def rellena(quad)
        quad.registro = @scope_actual.quads.length
    end

    def genera(w,x,y,z)
        tmp = Quad.new(w,x,y,z)
        @scope_actual.quads.push tmp
        tmp
    end

    def fun_prepare cual
        @funToCall.push cual
        @pOper.push "("
    end
        

    def fun_call
        if @funToCall.last == nil
            p "Compile Error"
            exit
        end
        cual = @funToCall.pop
        if(cual == "print")
            genera(Phast::PRT,nil,nil,nil)
        elsif(cual == "println")
            genera(Phast::PRTLN,nil,nil,nil)
        else
            @pFnCall.push genera(Phast::CALL,nil,nil,cual)
            tmp = Var.new(nil,nil,nil,@scope_actual.temporales.length,nil)
            @scope_actual.temporales.push tmp
            @pOperandos.push tmp
            genera(Phast::REV,nil,nil,tmp)
        end
        @pOper.pop
    end

    def argument
        genera(Phast::ARG,nil,nil,@pOperandos.pop)
    end

    def return_quad
        genera(Phast::RET,nil,nil,@pOperandos.last)
    end

    def end_fun
        return_quad
    end
    
    def param variable
        genera(Phast::PAR,nil,nil,variable)
    end
    
    def fun1 cual
        @pOperandos.push cual
    end

    def fun2
        @pOper.push Phast.op_to_inst(@curr_token[1])
    end

    def fun3(nivel)
        # puts "Checar el top de Poper tiene operador pendiente"
        if !@pOper.empty?
            op = @pOper.last
            case
            when nivel == 0
                if(op == Phast::MUL || op == Phast::DIV)
                    fun3_aux
                end
            when nivel == 1
                if(op == Phast::SUM || op == Phast::REST)
                    fun3_aux
                end
            when nivel == 2
                if(op == Phast::AND || op == Phast::OR || op == Phast::GT || op == Phast::LT || op == Phast::ELT || op == Phast::EGT || op == Phast::EQ)
                    fun3_aux
                end
            when nivel == 3
                if(op == Phast::ASIG)
                    @pOper.pop
                    oper = @pOperandos.pop
                    oper1 = @pOperandos.last
                    genera(op, oper, nil, oper1)
                end
            end
        end
    end

    def fun3_aux
        op = @pOper.pop
        oper = @pOperandos.pop
        oper1 = @pOperandos.pop
        tmp = Var.new(nil,nil,nil,@scope_actual.temporales.length,nil)
        @scope_actual.temporales.push tmp
        @pOperandos.push tmp

        genera(op, oper1, oper, @pOperandos.last)
    end

    def fun4
        @pOper.push "("
    end
    def fun5
        @pOper.pop
    end

    def if_quad(step)
        case
        when step == 1
            condicion = @pOperandos.pop
            @pSaltos.push genera(Phast::GOTOF, condicion, nil, nil)
        when step ==  2
            rellena(@pSaltos.pop)
        when step == 3
            f = @pSaltos.pop
            @pSaltos.push genera(Phast::GOTO, nil, nil, nil)
            rellena(f)
        end
    end

    def while_quad(step)
        case
        when step == 1
            @pSaltos.push @scope_actual.quads.length #Valor deshechable
        when step ==  2
            condicion = @pOperandos.pop
            @pSaltos.push genera(Phast::GOTOF, condicion, nil, nil)
        when step == 3
            f = @pSaltos.pop
            genera(Phast::GOTO, nil, nil, @pSaltos.pop)
            rellena(f)
        end
    end

    def do_while_quad(step)
        case
        when step == 1
            @pSaltos.push @scope_actual.quads.length
        when step ==  2
            condicion = @pOperandos.pop
            genera(Phast::GOTOV, condicion, nil, @pSaltos.pop)
        end
    end

    def process_output

        @reg_counter = 0 #TODO
        @mem_offset = 0 #TODO

        @salida = [0]

        @salida.push @scopes[:constantes].variables.length
        @salida.push @scopes[:global].variables.length
        @salida.push @scopes[:global].temporales.length

        @scopes[:constantes].variables.each do |k,c|
            @salida.push "#{c.direccion_virtual}\t#{c.tipoDato}\t#{c.valor}"
        end

        scope_global = @scopes.delete(:global)
        scope_constantes = @scopes.delete(:constantes)
        
        @scopes.each do |key, s|
            s.registro = @reg_counter
            @mem_offset = s.variables.length
            s.temporales.each do |v|
                v.direccion_virtual += @mem_offset
            end
            print_quads s.quads
        end

        @mem_offset = 0 #scope_constantes.variables.length
        #Correr variables
        # scope_global.variables.each do |k,v|
        #     v.direccion_virtual += @mem_offset
        # end
        @mem_offset += scope_global.variables.length
        scope_global.temporales.each do |v|
            v.direccion_virtual += @mem_offset
        end
        
        @salida[0] = @reg_counter
        print_quads scope_global.quads

        @pFnCall.each do |q|
            q.op1 = @scopes[q.registro].variables.length
            q.op2 = @scopes[q.registro].temporales.length
            q.registro = @scopes[q.registro].registro
        end

        puts @salida

    end

    def print_quads(quads)
        reg_offset = @reg_counter
        until quads.empty?
            quad = quads.shift
            quad.saltos reg_offset
            @salida.push quad
            @reg_counter += 1
        end
    end

    def on_error(t,val,vstack)
        raise ParseError, sprintf("\nError de sintaxis. Se encontro %s (%s) inesperado en la linea #{$lineno}", val.inspect, token_to_str(t) || '?')
    end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    13,    22,     2,    23,   -35,    78,    79,    25,    26,    27,
    28,   150,   116,    13,    22,   113,    23,   -35,    74,    75,
    25,    26,    27,    28,    31,    32,    87,    33,    89,   150,
   110,    34,    35,    36,    37,    38,    39,    31,    32,    31,
    33,    78,    79,    38,    34,    35,    36,    37,    38,    39,
    13,    22,   105,    23,   -35,    33,   192,    25,    26,    27,
    28,    38,   104,    13,    22,   122,    23,   -35,    74,    75,
    25,    26,    27,    28,    31,    32,   102,    33,   124,   127,
   128,    34,    35,    36,    37,    38,    39,    31,    32,   101,
    33,   131,   132,   133,    34,    35,    36,    37,    38,    39,
    13,    22,   104,    23,   -35,    89,   140,    25,    26,    27,
    28,   141,   143,    13,    22,   144,    23,   -35,   145,    97,
    25,    26,    27,    28,    31,    32,   114,    33,    93,    92,
    90,    34,    35,    36,    37,    38,    39,    31,    32,    60,
    33,   156,   157,    59,    34,    35,    36,    37,    38,    39,
    13,    22,   159,    23,   -35,   161,   162,    25,    26,    27,
    28,    58,   166,    13,    22,    55,    23,   -35,   -43,   169,
    25,    26,    27,    28,    31,    32,    49,    33,   172,    43,
   175,    34,    35,    36,    37,    38,    39,    31,    32,   140,
    33,   178,   179,   180,    34,    35,    36,    37,    38,    39,
    22,   181,    23,   183,   184,    41,    25,    26,    27,    28,
    22,   188,    23,    40,   193,   194,    25,    26,    27,    28,
    22,   161,    23,    31,    32,     3,    25,    26,    27,    28,
    22,   172,    23,    31,    32,   198,    25,    26,    27,    28,
    22,   nil,    23,    31,    32,   nil,    25,    26,    27,    28,
    22,   nil,    23,    31,    32,   nil,    25,    26,    27,    28,
    22,   -57,    23,    31,    32,   nil,    25,    26,    27,    28,
   nil,   nil,   nil,    31,    32,    64,    65,    66,    67,    68,
    69,    70,    71,    31,    32,    22,   nil,    23,   nil,   -79,
   nil,    25,    26,    27,    28,    22,   nil,    23,   nil,   nil,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,    22,   nil,    23,    31,    32,
   nil,    25,    26,    27,    28,   nil,   nil,   nil,    31,    32,
    25,    26,    27,    28,   nil,   nil,   nil,   nil,    31,    32,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    31,    32,    64,
    65,    66,    67,    68,    69,    70,    71 ]

racc_action_check = [
   192,   192,     0,   192,   192,    47,    47,   192,   192,   192,
   192,   148,    96,    93,    93,    94,    93,    93,    46,    46,
    93,    93,    93,    93,   192,   192,    52,   192,    52,   132,
    91,   192,   192,   192,   192,   192,   192,    93,    93,    87,
    93,   136,   136,   148,    93,    93,    93,    93,    93,    93,
     2,     2,    85,     2,     2,   185,   185,     2,     2,     2,
     2,   132,    82,   156,   156,   106,   156,   156,   135,   135,
   156,   156,   156,   156,     2,     2,    81,     2,   108,   111,
   112,     2,     2,     2,     2,     2,     2,   156,   156,    80,
   156,   114,   115,   116,   156,   156,   156,   156,   156,   156,
   181,   181,   121,   181,   181,   122,   125,   181,   181,   181,
   181,   126,   128,   159,   159,   129,   159,   159,   130,    61,
   159,   159,   159,   159,   181,   181,    95,   181,    57,    56,
    54,   181,   181,   181,   181,   181,   181,   159,   159,    39,
   159,   142,   143,    38,   159,   159,   159,   159,   159,   159,
   141,   141,   145,   141,   141,   146,   147,   141,   141,   141,
   141,    37,   155,     5,     5,    33,     5,     5,    23,   158,
     5,     5,     5,     5,   141,   141,    21,   141,   160,     6,
   164,   141,   141,   141,   141,   141,   141,     5,     5,   165,
     5,   166,   167,   168,     5,     5,     5,     5,     5,     5,
    50,   169,    50,   172,   174,     4,    50,    50,    50,    50,
    13,   182,    13,     3,   186,   187,    13,    13,    13,    13,
   144,   189,   144,    50,    50,     1,   144,   144,   144,   144,
    58,   195,    58,    13,    13,   196,    58,    58,    58,    58,
    92,   nil,    92,   144,   144,   nil,    92,    92,    92,    92,
    99,   nil,    99,    58,    58,   nil,    99,    99,    99,    99,
    90,    90,    90,    92,    92,   nil,    90,    90,    90,    90,
   nil,   nil,   nil,    99,    99,   134,   134,   134,   134,   134,
   134,   134,   134,    90,    90,    49,   nil,    49,   nil,    49,
   nil,    49,    49,    49,    49,   157,   nil,   157,   nil,   nil,
   nil,   157,   157,   157,   157,   100,   nil,   100,    49,    49,
   nil,   100,   100,   100,   100,   140,   nil,   140,   157,   157,
   nil,   140,   140,   140,   140,    55,   nil,    55,   100,   100,
   nil,    55,    55,    55,    55,   101,   nil,   101,   140,   140,
   nil,   101,   101,   101,   101,   113,   nil,   113,    55,    55,
   nil,   113,   113,   113,   113,   104,   nil,   104,   101,   101,
   nil,   104,   104,   104,   104,   107,   nil,   107,   113,   113,
   nil,   107,   107,   107,   107,    98,   nil,    98,   104,   104,
   nil,    98,    98,    98,    98,   nil,   nil,   nil,   107,   107,
   161,   161,   161,   161,   nil,   nil,   nil,   nil,    98,    98,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   161,   161,    45,
    45,    45,    45,    45,    45,    45,    45 ]

racc_action_pointer = [
     0,   225,    45,   213,   202,   158,   175,   nil,   nil,   nil,
   nil,   nil,   nil,   204,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   167,   nil,   162,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   159,   nil,   nil,   nil,   155,   135,   131,
   nil,   nil,   nil,   nil,   nil,   392,    -7,   -22,   nil,   279,
   194,   nil,    17,   nil,   124,   319,   123,    95,   224,   nil,
   nil,   115,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    58,    66,    46,   nil,   nil,    45,   nil,    10,   nil,   nil,
   254,    23,   234,     8,    11,   120,   -30,   nil,   369,   244,
   299,   329,   nil,   nil,   349,   nil,    55,   359,    71,   nil,
   nil,    72,    46,   339,    83,    59,    85,   nil,   nil,   nil,
   nil,    86,    94,   nil,   nil,    90,    78,   nil,    76,   111,
   111,   nil,    21,   nil,   258,    43,    14,   nil,   nil,   nil,
   309,   145,   108,   136,   214,   119,   112,   122,     3,   nil,
   nil,   nil,   nil,   nil,   nil,   128,    58,   289,   162,   108,
   162,   378,   nil,   nil,   169,   173,   156,   158,   186,   168,
   nil,   nil,   195,   nil,   200,   nil,   nil,   nil,   nil,   nil,
   nil,    95,   177,   nil,   nil,    23,   210,   181,   nil,   178,
   nil,   nil,    -5,   nil,   nil,   215,   201,   nil,   nil ]

racc_action_default = [
  -122,  -122,    -3,  -122,  -122,    -3,  -122,    -5,    -6,    -7,
    -8,    -9,   -10,   -35,   -13,   -14,   -15,   -21,   -27,   -33,
   -34,  -122,   -37,   -40,   -50,   -51,   -52,   -53,   -54,   -73,
   -74,   -75,   -76,  -122,   -92,   -95,   -98,  -122,  -122,  -122,
   199,    -1,    -2,    -4,   -11,   -20,   -26,   -32,   -36,   -35,
   -35,   -39,   -49,   -42,  -122,   -35,  -122,  -122,   -35,  -100,
  -103,  -122,   -16,   -17,   -61,   -62,   -63,   -64,   -65,   -66,
   -67,   -68,   -22,   -23,   -69,   -70,   -28,   -29,   -71,   -72,
   -73,  -122,   -81,   -82,   -84,  -122,   -41,  -122,   -46,   -47,
   -35,  -122,   -35,    -3,  -122,  -122,  -113,   -12,   -35,   -35,
   -35,   -35,   -77,   -78,   -35,   -38,  -122,   -35,  -122,   -55,
   -85,  -122,  -122,   -35,  -116,  -122,  -122,   -18,   -24,   -30,
   -83,   -81,   -49,   -48,   -44,   -60,  -122,   -93,  -122,  -122,
  -122,  -114,  -106,  -112,   -20,   -26,   -32,   -80,   -45,   -56,
   -35,    -3,  -122,  -122,   -35,  -122,  -121,  -122,  -106,  -107,
  -108,   -19,   -25,   -31,   -58,  -122,    -3,   -35,  -122,    -3,
  -119,  -122,  -104,  -105,  -111,   -60,   -89,  -122,  -122,  -122,
  -101,  -115,  -122,  -120,  -122,  -110,   -59,   -86,   -87,   -94,
   -96,    -3,  -122,  -117,  -109,  -122,  -122,  -122,  -102,  -121,
   -88,   -90,    -3,   -97,   -99,  -119,  -122,  -118,   -91 ]

racc_goto_table = [
     4,    44,    88,    42,    62,    76,    80,    72,    82,   160,
   139,    94,   171,   149,   103,   147,    54,   119,    99,    47,
   100,   136,   173,    48,    50,    51,    86,    53,    52,   149,
   108,   163,   135,    46,   118,   107,   134,    84,    85,   125,
   165,    81,    98,    91,   106,    45,   177,   197,   126,   190,
   176,   117,   195,   137,   185,    56,   142,    57,   186,   130,
    95,    80,   182,   121,   115,    61,    96,   174,   164,   191,
     1,   146,   138,   189,   nil,   nil,   nil,   nil,   109,   nil,
   111,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   120,
   nil,   112,    84,   151,   153,   123,   152,   nil,   nil,   nil,
   nil,   129,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   154,   nil,
   nil,   nil,   158,   nil,   nil,   nil,   nil,   nil,   nil,   155,
   nil,   nil,   nil,   nil,   nil,   168,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   167,   nil,   nil,   170,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   187,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   196 ]

racc_goto_check = [
     2,     4,    44,     2,    15,    27,    43,    21,    52,    72,
    47,    14,    73,    12,    53,    67,    42,    26,    24,    28,
    30,    31,    33,    34,    36,    37,    38,    39,    40,    12,
    41,    67,    25,    22,    20,    45,    19,     4,     4,    48,
    49,    51,    18,     4,    43,    16,    55,    73,    56,    57,
    47,    14,    72,    53,    58,    59,    60,    61,    62,    63,
    64,    43,    65,    52,    66,    11,    68,    70,    71,     8,
     1,    74,    44,    75,   nil,   nil,   nil,   nil,     4,   nil,
     4,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,
   nil,     2,     4,    15,    27,     4,    21,   nil,   nil,   nil,
   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,   nil,
   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   nil,   nil,     4,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     2 ]

racc_goto_pointer = [
   nil,    70,    -2,   nil,   -12,   nil,   nil,   nil,  -116,   nil,
   nil,    21,  -119,   nil,   -47,   -41,    29,   nil,   -21,   -81,
   -65,   -39,    16,   nil,   -55,   -86,   -83,   -42,     1,   nil,
   -57,   -98,   nil,  -139,     2,   nil,     2,     2,   -26,     4,
     5,   -60,    -7,   -43,   -50,   -54,   nil,  -115,   -70,  -114,
   nil,    -8,   -41,   -68,   nil,  -120,   -62,  -136,  -124,    21,
   -71,    22,  -122,   -55,     1,  -108,   -32,  -117,     6,   nil,
   -97,   -82,  -137,  -148,   -60,  -110 ]

racc_goto_default = [
   nil,   nil,   nil,     5,     6,     7,     8,     9,    10,    11,
    12,   nil,    14,    15,    16,   nil,   nil,    63,   nil,   nil,
    17,   nil,   nil,    73,   nil,   nil,    18,   nil,   nil,    77,
   nil,   nil,    19,    20,   nil,    21,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    29,   nil,   nil,    24,   nil,   nil,   nil,
    30,   nil,   nil,   nil,    83,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   148,
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 45, :_reduce_1,
  2, 46, :_reduce_none,
  0, 46, :_reduce_none,
  2, 47, :_reduce_4,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_10,
  0, 55, :_reduce_11,
  4, 47, :_reduce_12,
  1, 54, :_reduce_none,
  1, 54, :_reduce_none,
  0, 60, :_reduce_15,
  3, 48, :_reduce_none,
  0, 62, :_reduce_17,
  0, 63, :_reduce_18,
  5, 59, :_reduce_none,
  0, 59, :_reduce_none,
  0, 66, :_reduce_21,
  3, 58, :_reduce_none,
  0, 68, :_reduce_23,
  0, 69, :_reduce_24,
  5, 65, :_reduce_none,
  0, 65, :_reduce_none,
  0, 72, :_reduce_27,
  3, 64, :_reduce_none,
  0, 74, :_reduce_29,
  0, 75, :_reduce_30,
  5, 71, :_reduce_none,
  0, 71, :_reduce_none,
  1, 70, :_reduce_none,
  1, 70, :_reduce_34,
  0, 79, :_reduce_35,
  2, 70, :_reduce_36,
  0, 80, :_reduce_37,
  4, 70, :_reduce_38,
  2, 76, :_reduce_none,
  0, 84, :_reduce_40,
  2, 81, :_reduce_none,
  1, 81, :_reduce_none,
  0, 86, :_reduce_43,
  4, 83, :_reduce_44,
  4, 82, :_reduce_none,
  1, 82, :_reduce_none,
  0, 89, :_reduce_47,
  3, 88, :_reduce_48,
  0, 88, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_51,
  1, 77, :_reduce_52,
  1, 77, :_reduce_53,
  1, 77, :_reduce_54,
  0, 92, :_reduce_55,
  3, 85, :_reduce_none,
  0, 85, :_reduce_none,
  0, 93, :_reduce_58,
  4, 91, :_reduce_none,
  0, 91, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 61, :_reduce_none,
  1, 67, :_reduce_none,
  1, 67, :_reduce_none,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 87, :_reduce_75,
  1, 94, :_reduce_76,
  3, 78, :_reduce_none,
  2, 95, :_reduce_none,
  0, 95, :_reduce_none,
  3, 97, :_reduce_none,
  0, 97, :_reduce_none,
  1, 96, :_reduce_82,
  3, 98, :_reduce_none,
  1, 98, :_reduce_none,
  0, 100, :_reduce_85,
  9, 52, :_reduce_86,
  0, 102, :_reduce_87,
  3, 99, :_reduce_none,
  0, 99, :_reduce_none,
  1, 101, :_reduce_none,
  3, 101, :_reduce_none,
  0, 103, :_reduce_92,
  0, 104, :_reduce_93,
  9, 49, :_reduce_94,
  0, 105, :_reduce_95,
  0, 106, :_reduce_96,
  11, 50, :_reduce_none,
  1, 51, :_reduce_none,
  11, 53, :_reduce_none,
  0, 108, :_reduce_100,
  0, 109, :_reduce_101,
  10, 56, :_reduce_none,
  0, 112, :_reduce_103,
  7, 57, :_reduce_none,
  2, 111, :_reduce_none,
  0, 111, :_reduce_none,
  1, 113, :_reduce_107,
  0, 115, :_reduce_108,
  4, 113, :_reduce_none,
  1, 114, :_reduce_none,
  0, 114, :_reduce_none,
  2, 110, :_reduce_none,
  0, 110, :_reduce_none,
  0, 118, :_reduce_114,
  4, 107, :_reduce_none,
  0, 107, :_reduce_none,
  0, 119, :_reduce_117,
  5, 117, :_reduce_none,
  0, 117, :_reduce_none,
  2, 116, :_reduce_120,
  0, 116, :_reduce_none ]

racc_reduce_n = 122

racc_shift_n = 199

racc_token_table = {
  false => 0,
  :error => 1,
  :PH_OT => 2,
  :PH_CT => 3,
  ";" => 4,
  :WORD_RETURN => 5,
  "(" => 6,
  ")" => 7,
  :ID => 8,
  "[" => 9,
  "]" => 10,
  :OP_ASIGN => 11,
  :STRING => 12,
  :WORD_TRUE => 13,
  :WORD_FALSE => 14,
  :WORD_NULL => 15,
  "," => 16,
  :OP_EQUAL => 17,
  :OP_NOT_EQUAL => 18,
  :OP_GREATER => 19,
  :OP_GREATER_EQUAL => 20,
  :OP_LESS => 21,
  :OP_LESS_EQUAL => 22,
  :WORD_AND => 23,
  :WORD_OR => 24,
  :OP_PLUS => 25,
  :OP_MINUS => 26,
  :OP_MULTIPLY => 27,
  :OP_DIVIDE => 28,
  :INT => 29,
  :FLOAT => 30,
  :OP_KEYVAL => 31,
  :WORD_IF => 32,
  "{" => 33,
  "}" => 34,
  :WORD_ELSE => 35,
  :WORD_WHILE => 36,
  :WORD_DO => 37,
  :VERBOSE_BLOCK => 38,
  :WORD_FOR => 39,
  :WORD_FUN => 40,
  :WORD_CLASS => 41,
  :WORD_EXTENDS => 42,
  "=" => 43 }

racc_nt_base = 44

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "PH_OT",
  "PH_CT",
  "\";\"",
  "WORD_RETURN",
  "\"(\"",
  "\")\"",
  "ID",
  "\"[\"",
  "\"]\"",
  "OP_ASIGN",
  "STRING",
  "WORD_TRUE",
  "WORD_FALSE",
  "WORD_NULL",
  "\",\"",
  "OP_EQUAL",
  "OP_NOT_EQUAL",
  "OP_GREATER",
  "OP_GREATER_EQUAL",
  "OP_LESS",
  "OP_LESS_EQUAL",
  "WORD_AND",
  "WORD_OR",
  "OP_PLUS",
  "OP_MINUS",
  "OP_MULTIPLY",
  "OP_DIVIDE",
  "INT",
  "FLOAT",
  "OP_KEYVAL",
  "WORD_IF",
  "\"{\"",
  "\"}\"",
  "WORD_ELSE",
  "WORD_WHILE",
  "WORD_DO",
  "VERBOSE_BLOCK",
  "WORD_FOR",
  "WORD_FUN",
  "WORD_CLASS",
  "WORD_EXTENDS",
  "\"=\"",
  "$start",
  "phast",
  "estatutos",
  "estatuto",
  "expresion",
  "bloque_while",
  "bloque_do",
  "bloque_verbose",
  "bloque_if",
  "bloque_for",
  "bloques_declarativos",
  "@1",
  "bloque_fun",
  "bloque_class",
  "comparando",
  "comparando_aux",
  "@2",
  "op_comp",
  "@3",
  "@4",
  "termino",
  "termino_aux",
  "@5",
  "op_term",
  "@6",
  "@7",
  "factor",
  "factor_aux",
  "@8",
  "op_fact",
  "@9",
  "@10",
  "llamada",
  "estatico",
  "arreglo",
  "@11",
  "@12",
  "tipo_llamada",
  "vars",
  "funcs",
  "@13",
  "argumentos",
  "@14",
  "int",
  "asign",
  "@15",
  "numero",
  "args_aux",
  "@16",
  "@17",
  "float",
  "arr_elems",
  "arr_elem",
  "arr_elems_aux",
  "arr_elem_wrapper",
  "else",
  "@18",
  "aux_else",
  "@19",
  "@20",
  "@21",
  "@22",
  "@23",
  "params",
  "@24",
  "@25",
  "class_extras",
  "class_body",
  "@26",
  "class_body_aux",
  "class_def_var_aux",
  "@27",
  "def_param",
  "params_aux",
  "@28",
  "@29" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_1(val, _values, result)
    
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_4(val, _values, result)
     vaciar_pOperandos 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_10(val, _values, result)
     disminuye_scope 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_11(val, _values, result)
    return_quad 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_12(val, _values, result)
     vaciar_pOperandos 
    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_15(val, _values, result)
    fun3 2
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_17(val, _values, result)
    fun2
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_18(val, _values, result)
    fun3 2
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_21(val, _values, result)
    fun3 1
    result
  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_23(val, _values, result)
    fun2
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_24(val, _values, result)
    fun3 1
    result
  end
.,.,

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_27(val, _values, result)
    fun3 0
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_29(val, _values, result)
    fun2
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_30(val, _values, result)
    fun3 0
    result
  end
.,.,

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_34(val, _values, result)
     fun1(llama_cte(@prev_token[1])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_35(val, _values, result)
     openArreglo 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_36(val, _values, result)
     closeArreglo 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_37(val, _values, result)
    fun4
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_38(val, _values, result)
    fun5
    result
  end
.,.,

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_40(val, _values, result)
     fun1(llame_var(@prev_token[1])) 
    result
  end
.,.,

# reduce 41 omitted

# reduce 42 omitted

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_43(val, _values, result)
     fun_prepare @prev_token[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_44(val, _values, result)
     fun_call 
    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_47(val, _values, result)
    fun2
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_48(val, _values, result)
    fun3 3
    result
  end
.,.,

# reduce 49 omitted

# reduce 50 omitted

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_51(val, _values, result)
     guarda_cte @curr_token[1], String(@curr_token[1]) , 4 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_52(val, _values, result)
     guarda_cte @curr_token[1], true , 1 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_53(val, _values, result)
     guarda_cte @curr_token[1], false , 1 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_54(val, _values, result)
     guarda_cte @curr_token[1], nil , 0 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_55(val, _values, result)
     argument 
    result
  end
.,.,

# reduce 56 omitted

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_58(val, _values, result)
     argument 
    result
  end
.,.,

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_75(val, _values, result)
     guarda_cte @curr_token[1], Integer(@curr_token[1]) , 2 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_76(val, _values, result)
     guarda_cte @curr_token[1], Float(@curr_token[1]) , 3 
    result
  end
.,.,

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

module_eval(<<'.,.,', 'parser.y', 105)
  def _reduce_82(val, _values, result)
     @pOperandos.pop 
    result
  end
.,.,

# reduce 83 omitted

# reduce 84 omitted

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_85(val, _values, result)
    if_quad 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_86(val, _values, result)
    if_quad 2
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_87(val, _values, result)
    if_quad 3
    result
  end
.,.,

# reduce 88 omitted

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_92(val, _values, result)
    while_quad 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_93(val, _values, result)
    while_quad 2
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_94(val, _values, result)
    while_quad 3
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_95(val, _values, result)
    do_while_quad 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_96(val, _values, result)
    do_while_quad 2
    result
  end
.,.,

# reduce 97 omitted

# reduce 98 omitted

# reduce 99 omitted

module_eval(<<'.,.,', 'parser.y', 118)
  def _reduce_100(val, _values, result)
     aumenta_scope @curr_token[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 118)
  def _reduce_101(val, _values, result)
     end_fun 
    result
  end
.,.,

# reduce 102 omitted

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_103(val, _values, result)
     aumenta_scope @curr_token[1] 
    result
  end
.,.,

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_107(val, _values, result)
     disminuye_scope 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 124)
  def _reduce_108(val, _values, result)
     llame_var @curr_token[1] 
    result
  end
.,.,

# reduce 109 omitted

# reduce 110 omitted

# reduce 111 omitted

# reduce 112 omitted

# reduce 113 omitted

module_eval(<<'.,.,', 'parser.y', 130)
  def _reduce_114(val, _values, result)
     param(llame_var(@curr_token[1])) 
    result
  end
.,.,

# reduce 115 omitted

# reduce 116 omitted

module_eval(<<'.,.,', 'parser.y', 132)
  def _reduce_117(val, _values, result)
     param(llame_var(@curr_token[1])) 
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_120(val, _values, result)
     fun1(llama_cte(@curr_token[1])) 
    result
  end
.,.,

# reduce 121 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Phast
